use library;

INSERT INTO `librarybranch` VALUES (1,'Arlington Library','203 Arlington Ave. at Warwick St. Brooklyn, NY11207'),(2,'Bay Ridge Library','7223 Ridge Blvd. at 73rd St. Brooklyn, NY11209'),(3,'Bedford Learning Center','496 Franklin Avenue Brooklyn, NY11238'),(4,'Bedford Library','496 Franklin Avenue Brooklyn, NY11238'),(5,'Borough Park Library','1265 43rd St. at 13th Ave. Brooklyn, NY11219'),(6,'Brighton Beach Library','16 Brighton First Rd. at Brighton Beach Ave. Brooklyn, NY11235'),(7,'Brooklyn Heights Library','280 Cadman Plaza West at Tillary St. Brooklyn, NY11201'),(8,'Brower Park Library','725 St. Marks Ave. at Nostrand Ave. Brooklyn, NY11216'),(9,'Brownsville Library','61 Glenmore Ave. at Watkins St. Brooklyn, NY11212'),(10,'Bushwick Library','340 Bushwick Ave. at Seigel St. Brooklyn, NY11206');

insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Amy','A',2,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Anne','U',1,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Ben','A',2,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Cody','U',3,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Brandon','A',5,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Jordan','U',6,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Nathan','A',7,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Alicia','U',8,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Bill','U',9,0);
insert into person(uname,usertype,preferredbranch,totalLoansMade) values('Jake','A',10,0);


insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Quién ayuda en casa? / Ricardo Alcántara   ilustrado por    Gusti","Alcántara, Ricardo.","8a ed.",3,"FICTION SPANISH ",8426319173,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Allen, Paul Marshall","4308 A","A Christian Rosenkreutz anthology",10,"BOOK",1,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Venezuela, a democracy","Allen, Henry Justin, 1868-1950.","1st ed.",9,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Venezuela, a democracy","Allen, Henry Justin, 1868-1950.","1st ed.",2,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Venezuela, a democracy","Allen, Henry Justin, 1868-1950.","1st ed.",1,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Home town","Amory, Cleveland.","[1st ed.]",6,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Home town","Amory, Cleveland.","[1st ed.]",8,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Home town","Amory, Cleveland.","[1st ed.]",10,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mid-east: world-center, yesterday, today, and tomorrow. Planned and edited by Ruth Nanda Anshen. Prepared with the collaboration of Ernest Jackh","Anshen, Ruth Nanda.","[1st ed.]",2,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mid-east: world-center, yesterday, today, and tomorrow. Planned and edited by Ruth Nanda Anshen. Prepared with the collaboration of Ernest Jackh","Anshen, Ruth Nanda.","[1st ed.]",1,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Wo shi shui? / pianxie Anxin   huitu Ouyangzhigang","Anxin.","Chu ban.",8,"CHINESE ",9620818199,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Wo shi shui? / pianxie Anxin   huitu Ouyangzhigang","Anxin.","Chu ban.",2,"CHINESE ",9620818199,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Wo shi shui? / pianxie Anxin   huitu Ouyangzhigang","Anxin.","Chu ban.",3,"CHINESE ",9620818199,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The three lives of Harriet Hubbard Ayer, by Margaret Hubbard Ayer and Isabella Taves","Ayer, Margaret Hubbard.","[1st ed.]",5,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The three lives of Harriet Hubbard Ayer, by Margaret Hubbard Ayer and Isabella Taves","Ayer, Margaret Hubbard.","[1st ed.]",7,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Canapés for the kitties / Marian Babson","Babson, Marian.","Softcover large print ed.",8,"FICTION ",1568955227,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Economic dynamics  an introduction [by] William J. Baumol. With a contribution by Ralph Turvey","Baumol, William J.","3rd ed.",2,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Economic dynamics  an introduction [by] William J. Baumol. With a contribution by Ralph Turvey","Baumol, William J.","3rd ed.",7,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Good bye, Ava","Bissell, Richard Pike.","[1st ed.]",2,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Good bye, Ava","Bissell, Richard Pike.","[1st ed.]",4,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Good bye, Ava","Bissell, Richard Pike.","[1st ed.]",5,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The warrior saint","Bodley, R. V. C. (Ronald Victor Courtenay), 1892-","[1st ed.]",9,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The warrior saint","Bodley, R. V. C. (Ronald Victor Courtenay), 1892-","[1st ed.]",4,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The warrior saint","Bodley, R. V. C. (Ronald Victor Courtenay), 1892-","[1st ed.]",1,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The community college","Bogue, Jesse Parker, 1889-1960.","1st ed.",8,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("T. E. Lawrence / Peter Brent   introd. by Elizabeth Longford","Brent, Peter Ludwig.","1st American ed.",2,"BOOK",0399115846,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("T. E. Lawrence / Peter Brent   introd. by Elizabeth Longford","Brent, Peter Ludwig.","1st American ed.",5,"BOOK",0399115846,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Before barbed wire / by Mark H. Brown and W. R. Felton   L. A. Huffman, photographer on horseback","Brown, Mark Herbert, 1900-","[1st ed.]",1,"SCIENCE ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Before barbed wire / by Mark H. Brown and W. R. Felton   L. A. Huffman, photographer on horseback","Brown, Mark Herbert, 1900-","[1st ed.]",10,"SCIENCE ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Men, women, and other anticlimaxes / Anatole Broyard","Broyard, Anatole.","1st American ed.",9,"BOOK",0416005314,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Report from part one. Prefaces by Don L. Lee and George Kent","Brooks, Gwendolyn, 1917-2000.","[1st ed.]",5,"BOOK",0910296820,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Report from part one. Prefaces by Don L. Lee and George Kent","Brooks, Gwendolyn, 1917-2000.","[1st ed.]",9,"BOOK",0910296820,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Violent summer / H.B. Broome","Broome, H. B.","1st ed.",2,"FICTION ",0385265670,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Violent summer / H.B. Broome","Broome, H. B.","1st ed.",4,"FICTION ",0385265670,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Violent summer / H.B. Broome","Broome, H. B.","1st ed.",9,"FICTION ",0385265670,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A choice of attitudes","Burr, Gray.","[1st ed.]",6,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The affairs of Flavie (Les Héritiers Euffe) tr. from the French by Jocelyn Godefroi","Chevallier, Gabriel, 1895-","[1st American ed.]",3,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Pien se mao / Cheng Yün-chʻin hsieh, Hu Ning-na hua","Cheng, Yün-chʻin.","Ti 1 pan.",1,"CHINESE ",7532025411,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Fieldiana: zoology memoirs","Chicago Natural History Museum.","v. 1- Feb. 28",2,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Fieldiana: zoology memoirs","Chicago Natural History Museum.","v. 1- Feb. 28",3,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A seed was sown  the life, philosophy, and writings of Oscar H. Geiger, founder of the Henry George School of Social Science","Clancy, Robert, 1904-","[2d ed.",3,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Systems of land tenure in various countries. A series of essays published under the sanction of the Cobden Club. Ed. by J. W. Probyn","Cobden Club (London, England)","New ed.",3,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Go, said the bird","Cotterell, Geoffrey, 1919-","[1st American ed.]",2,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Go, said the bird","Cotterell, Geoffrey, 1919-","[1st American ed.]",10,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A synopsis of biology","Crow, William Bernard.","2d ed.",2,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A synopsis of biology","Crow, William Bernard.","2d ed.",4,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The literature of The United States / Marcus Cunliffe","Cunliffe, Marcus.","4th ed.",6,"BOOK",0140225145,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The literature of The United States / Marcus Cunliffe","Cunliffe, Marcus.","4th ed.",1,"BOOK",0140225145,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The literature of The United States / Marcus Cunliffe","Cunliffe, Marcus.","4th ed.",8,"BOOK",0140225145,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Complete poems. With an introduction by Osbert Sitwell and a foreword by Daniel George","Davies, W. H. (William Henry), 1871-1940.","[1st American ed.]",10,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Envy the frightened","Dayan, Yaël, 1939-","[1st ed.]",1,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Envy the frightened","Dayan, Yaël, 1939-","[1st ed.]",8,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Envy the frightened","Dayan, Yaël, 1939-","[1st ed.]",2,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Temptation / Jude Deveraux","Deveraux, Jude.","Bookspan large print ed.",5,"FICTION ",0739413465,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("All-American English / J. L. Dillard","Dillard, J. L. (Joey Lee), 1924-","1st ed.",3,"BOOK",0394489659,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("All-American English / J. L. Dillard","Dillard, J. L. (Joey Lee), 1924-","1st ed.",4,"BOOK",0394489659,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Perspectives on Pakistan. Edited by Anwar S. Dil","Dil, Anwar S.","[1st ed.]",9,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Perspectives on Pakistan. Edited by Anwar S. Dil","Dil, Anwar S.","[1st ed.]",10,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Perspectives on Pakistan. Edited by Anwar S. Dil","Dil, Anwar S.","[1st ed.]",2,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Six upon the world  toward an American culture for an industrial age","Douglass, Paul.","[1st ed.]",5,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("REBECCA","DAPHNE DU MAURIER.","T",4,"AUDIO ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("REBECCA","DAPHNE DU MAURIER.","T",5,"AUDIO ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("REBECCA","DAPHNE DU MAURIER.","T",10,"AUDIO ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Literature and the press : a history of printing, printed media, and their relation to literature / Louis Dudek","Dudek, Louis, 1918-","1st ed.",9,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Literature and the press : a history of printing, printed media, and their relation to literature / Louis Dudek","Dudek, Louis, 1918-","1st ed.",5,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Olympe de Clèves  a romance of the court of Louis the Fifteenth","Dumas, Alexandre, 1802-1870.","Ed. de Médicis.",7,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Olympe de Clèves  a romance of the court of Louis the Fifteenth","Dumas, Alexandre, 1802-1870.","Ed. de Médicis.",1,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Olympe de Clèves  a romance of the court of Louis the Fifteenth","Dumas, Alexandre, 1802-1870.","Ed. de Médicis.",6,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Alone he went, by Anthony Richardson","Embry, Basil Edward, Sir, 1902-","[1st American ed.]",1,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Reinforced concrete fundamentals with emphasis on ultimate strength","Ferguson, Phil Moss, 1899-","2d ed.",10,"BOOK",10.50,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Reinforced concrete fundamentals with emphasis on ultimate strength","Ferguson, Phil Moss, 1899-","2d ed.",6,"BOOK",10.50,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Atlas of economic structure and policies [by] P. Sargant Florence","Florence, P. Sargant (Philip Sargant), 1890-","[1st ed.]",7,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A cow is too much trouble in Los Angeles","Foster, Joseph.","[1st ed.]",7,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A cow is too much trouble in Los Angeles","Foster, Joseph.","[1st ed.]",1,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A cow is too much trouble in Los Angeles","Foster, Joseph.","[1st ed.]",9,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Jimmy Carter, in search of the great White House / by Betty Glad","Glad, Betty.","1st ed.",5,"BOOK",0393075273,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("What I wear / Heidi Goennel","Goennel, Heidi.","1st ed.",4,"JOURNAL ",0688141471,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("What I wear / Heidi Goennel","Goennel, Heidi.","1st ed.",1,"JOURNAL ",0688141471,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("C.S. Lewis","Green, Roger Lancelyn.","[1st American ed.]",7,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Your child today and tomorrow : some practical counsel for parents / by Sidonie Matsner Gruenberg ..","Gruenberg, Sidonie Matsner, 1881-","4th rev. ed.",10,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Your child today and tomorrow : some practical counsel for parents / by Sidonie Matsner Gruenberg ..","Gruenberg, Sidonie Matsner, 1881-","4th rev. ed.",6,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Your child today and tomorrow : some practical counsel for parents / by Sidonie Matsner Gruenberg ..","Gruenberg, Sidonie Matsner, 1881-","4th rev. ed.",1,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Seven voices  seven Latin American writers talk to Rita Guibert. Translated from the Spanish by Frances Partridge. Introd. by Emir Rodríguez Monegal","Guibert, Rita.","[1st ed.]",2,"BOOK",0394468880,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The last summer, a novel","Gunn, Elizabeth.","[1st American ed.]",8,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The last summer, a novel","Gunn, Elizabeth.","[1st American ed.]",5,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mozart : a cultural biography / Robert W. Gutman","Gutman, Robert W.","1st Harvest ed.",8,"BOOK",0156011719,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mozart : a cultural biography / Robert W. Gutman","Gutman, Robert W.","1st Harvest ed.",7,"BOOK",0156011719,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The grudge fight","Hale, John.","[1st American ed.]",1,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Sandy Koufax, strikeout king","Hano, Arnold, 1922-","[Rev. ed.]",10,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Sandy Koufax, strikeout king","Hano, Arnold, 1922-","[Rev. ed.]",7,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Humbug  the art of P. T. Barnum","Harris, Neil, 1938-","[1st ed.]",7,"BOOK",0316348236,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Humbug  the art of P. T. Barnum","Harris, Neil, 1938-","[1st ed.]",4,"BOOK",0316348236,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mosaic in the fountain","Harding, Bertita.","[1st ed.]",7,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mosaic in the fountain","Harding, Bertita.","[1st ed.]",5,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mosaic in the fountain","Harding, Bertita.","[1st ed.]",2,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Shi jian / zuo zhe Wan Ping   Hui tu Ye Ren","He, Yuping.","Chu ban.",2,"CHINESE ",9620816595,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A fellowship of discontent [by] Hans J. Hillerbrand","Hillerbrand, Hans Joachim.","[1st ed.]",8,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Nothing if not critical : selected essays on art and artists / Robert Hughes","Hughes, Robert, 1938-","1st ed.",4,"BOOK",0394580265,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Evidence of love, a novel","Jacobson, Dan.","[1st ed.]",10,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Evidence of love, a novel","Jacobson, Dan.","[1st ed.]",1,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Evidence of love, a novel","Jacobson, Dan.","[1st ed.]",2,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The science of physics in lithography. Illus. by Edith Strauss and the author","Jaffe, Erwin A.","[1st ed.]",10,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The book of the short story, ed. by Henry Seidel Canby and Robeson Bailey","Jessup, Alexander.","New and enl. ed.",3,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The book of the short story, ed. by Henry Seidel Canby and Robeson Bailey","Jessup, Alexander.","New and enl. ed.",4,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Chemical and technical stenography  technical Gregg stenography with special outlines and textual matter for the fields of chemistry and metallurgy","Kanegis, James.","1st ed.",3,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Thomas Kelly, a biography [by] Richard M. Kelly","Kelly, Richard Michael, 1937-","[1st. ed.]",8,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Thomas Kelly, a biography [by] Richard M. Kelly","Kelly, Richard Michael, 1937-","[1st. ed.]",10,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The custom house","King, Francis Henry.","[1st ed. in the U.S.A.]",2,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The custom house","King, Francis Henry.","[1st ed. in the U.S.A.]",4,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The custom house","King, Francis Henry.","[1st ed. in the U.S.A.]",6,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("An historical relation of Ceylon. With an introd. by S. D. Saparamadu","Knox, Robert, 1640?-1720.","[1 st ed.",3,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("An historical relation of Ceylon. With an introd. by S. D. Saparamadu","Knox, Robert, 1640?-1720.","[1 st ed.",6,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Kings and philosophers, 1689-1789 /  Leonard Krieger","Krieger, Leonard.","[1st ed.]",9,"BOOK",393099059,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Kings and philosophers, 1689-1789 /  Leonard Krieger","Krieger, Leonard.","[1st ed.]",1,"BOOK",393099059,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Language and its structure  some fundamental linguistic concepts [by] Ronald W. Langacker","Langacker, Ronald W.","2d ed.",6,"BOOK",015549192,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Language and its structure  some fundamental linguistic concepts [by] Ronald W. Langacker","Langacker, Ronald W.","2d ed.",3,"BOOK",015549192,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Larson, Ron, 1941-"," 1990 q515 L","Calculus with analytic geometry / Roland E. Larson",8,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Larson, Ron, 1941-"," 1990 q515 L","Calculus with analytic geometry / Roland E. Larson",7,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The journal of Augustus Pelletier : the Lewis and Clark Expedition / by Kathryn Lasky","Lasky, Kathryn.","1st ed.",9,"JOURNAL FICTION ",0590684892,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The journal of Augustus Pelletier : the Lewis and Clark Expedition / by Kathryn Lasky","Lasky, Kathryn.","1st ed.",6,"JOURNAL FICTION ",0590684892,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Chʻin yung / Li Pi-hua","Li, Bihua.","Chʻu pan.",6,"FICTION CHINESE ",9622574246,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("In the dark body of metamorphosis & other poems. Translated by I. L. Salomon","Luzi, Mario.","[1st ed.]",5,"BOOK",0393043916,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("In the dark body of metamorphosis & other poems. Translated by I. L. Salomon","Luzi, Mario.","[1st ed.]",4,"BOOK",0393043916,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The political and constitutional ideas of the Philippine revolution. With an introd. by Leopoldo Y. Yabes","Majul, Cesar Adib.","Rev. ed.",9,"BOOK",0882110535,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The political and constitutional ideas of the Philippine revolution. With an introd. by Leopoldo Y. Yabes","Majul, Cesar Adib.","Rev. ed.",6,"BOOK",0882110535,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Assignment to austerity  an American family in Britain, by Herbert and Nancie Matthews","Matthews, Herbert Lionel, 1900-","[1st ed.]",8,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Assignment to austerity  an American family in Britain, by Herbert and Nancie Matthews","Matthews, Herbert Lionel, 1900-","[1st ed.]",4,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Assignment to austerity  an American family in Britain, by Herbert and Nancie Matthews","Matthews, Herbert Lionel, 1900-","[1st ed.]",3,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Edward Palmer, plant explorer of the American West","McVaugh, Rogers, 1909-","[1st ed.].",5,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Flying","Millett, Kate.","[1st ed.]",3,"BOOK",0394489853,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Flying","Millett, Kate.","[1st ed.]",10,"BOOK",0394489853,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Flying","Millett, Kate.","[1st ed.]",9,"BOOK",0394489853,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Skye : the women of Primrose Creek / Linda Lael Miller","Miller, Linda Lael.","Large print ed.",10,"FICTION ",1587241447,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Skye : the women of Primrose Creek / Linda Lael Miller","Miller, Linda Lael.","Large print ed.",6,"FICTION ",1587241447,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Skye : the women of Primrose Creek / Linda Lael Miller","Miller, Linda Lael.","Large print ed.",8,"FICTION ",1587241447,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Helmet and wasps  [a novel","Mott, Michael.","1st American ed.]",5,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Helmet and wasps  [a novel","Mott, Michael.","1st American ed.]",10,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Science experiments with electricity / Sally Nankivell-Aston and Dorothy Jackson   [photography by Ray Moller]","Nankivell-Aston, Sally.","1st American ed.",6,"JOURNAL ",0531145808,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Science experiments with electricity / Sally Nankivell-Aston and Dorothy Jackson   [photography by Ray Moller]","Nankivell-Aston, Sally.","1st American ed.",5,"JOURNAL ",0531145808,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Portrait of a marriage","Nicolson, Nigel.","[1st ed.]",2,"BOOK",0689105746,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Portrait of a marriage","Nicolson, Nigel.","[1st ed.]",1,"BOOK",0689105746,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Portrait of a marriage","Nicolson, Nigel.","[1st ed.]",3,"BOOK",0689105746,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The general. Translated from the German by Constantine Fitzgibbon","Opitz, Karlludwig, 1914-","[1st American ed.]",1,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The general. Translated from the German by Constantine Fitzgibbon","Opitz, Karlludwig, 1914-","[1st American ed.]",4,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The women who make our novels","Overton, Grant Martin, 1887-1930.","New and completely rev. ed.",4,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The women who make our novels","Overton, Grant Martin, 1887-1930.","New and completely rev. ed.",6,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The women who make our novels","Overton, Grant Martin, 1887-1930.","New and completely rev. ed.",1,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Joe Petrosino. Translated by Charles Lam Markmann","Petacco, Arrigo.","[1st American ed.]",10,"BOOK",0025951602,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("During the storm and other stories / by Anna B. Pierson","Pierson, Anna B.","1st ed.",10,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Percy Bysshe Shelley / by Donald H. Reiman","Reiman, Donald H.","Updated ed.",1,"BOOK",0805769811,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Percy Bysshe Shelley / by Donald H. Reiman","Reiman, Donald H.","Updated ed.",5,"BOOK",0805769811,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Percy Bysshe Shelley / by Donald H. Reiman","Reiman, Donald H.","Updated ed.",10,"BOOK",0805769811,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("McGinnis speaks","Rooney, Frank.","[1st ed.]",1,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The few and the many. Translated from the German by Richard and Clara Winston","Sahl, Hans.","[1st ed.]",6,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The few and the many. Translated from the German by Richard and Clara Winston","Sahl, Hans.","[1st ed.]",1,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The few and the many. Translated from the German by Richard and Clara Winston","Sahl, Hans.","[1st ed.]",5,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The Chinese  and, Dr. Fish","Schisgal, Murray, 1926-","[Acting ed.]",7,"BOOK",0822202077,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The Chinese  and, Dr. Fish","Schisgal, Murray, 1926-","[Acting ed.]",2,"BOOK",0822202077,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The Chinese  and, Dr. Fish","Schisgal, Murray, 1926-","[Acting ed.]",5,"BOOK",0822202077,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Foundations of the non-linear mechanics of continua [by] L.I. Sedov. Translated from the Russian by Rebecca Schoenfeld-Reiner. English translation edi","Sedov, L. I. (Leonid Ivanovich), 1907-","[1st ed.]",7,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Foundations of the non-linear mechanics of continua [by] L.I. Sedov. Translated from the Russian by Rebecca Schoenfeld-Reiner. English translation edi","Sedov, L. I. (Leonid Ivanovich), 1907-","[1st ed.]",9,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The Sikligars of Punjab, a gypsy tribe, by Sher Singh  Sher. ","Sher, Sher Singh, 1924-","[1st ed.]",7,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Toyland, by Mark Smith","Smith, Mark, 1935-","[1st ed.]",5,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Toyland, by Mark Smith","Smith, Mark, 1935-","[1st ed.]",10,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The gate  [a novel","Sourian, Peter, 1933-","1st ed.]",6,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The Bacchae of Euripides: a communion rite, by Wole Soyinka","Soyinka, Wole.","[1st American ed.]",5,"BOOK",0393043967,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The Bacchae of Euripides: a communion rite, by Wole Soyinka","Soyinka, Wole.","[1st American ed.]",4,"BOOK",0393043967,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The Bacchae of Euripides: a communion rite, by Wole Soyinka","Soyinka, Wole.","[1st American ed.]",1,"BOOK",0393043967,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("La Grande Thérèse : the greatest scandal of the century / Hilary Spurling","Spurling, Hilary.","1st American ed.",4,"BOOK",006019622,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Some are born great","St. Johns, Adela Rogers.","[1st ed.]",5,"BOOK",0385087691,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Some are born great","St. Johns, Adela Rogers.","[1st ed.]",9,"BOOK",0385087691,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Rose and vine / by Rachel Annand Taylor","Taylor, Rachel Annand, 1876-","2d ed.",7,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Album. Pref. by Andre George. Designed and edited by Jeanne Mortier and Marie-Louise Aboux from the publications and letters of Pierre Teilhard de Cha","Teilhard de Chardin, Pierre.","[1st ed.]",4,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The house in Milan. Translated by Sidney Alexander","Testori, Giovanni.","[1st American ed.]",6,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Tom Harris","Themerson, Stefan.","[1st American ed.]",10,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Tom Harris","Themerson, Stefan.","[1st American ed.]",9,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The secret life of plants [by] Peter Tompkins and Christopher Bird","Tompkins, Peter.","[1st ed.]",6,"BOOK",0060143266,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The secret life of plants [by] Peter Tompkins and Christopher Bird","Tompkins, Peter.","[1st ed.]",3,"BOOK",0060143266,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The secret life of plants [by] Peter Tompkins and Christopher Bird","Tompkins, Peter.","[1st ed.]",9,"BOOK",0060143266,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Europe","Van Valkenburg, Samuel, 1891-","2d ed.",1,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Europe","Van Valkenburg, Samuel, 1891-","2d ed.",3,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Europe","Van Valkenburg, Samuel, 1891-","2d ed.",7,"BOOK",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The horses of the sun [by] Oriel Malet [pseud","Malet, Oriel.","1st American ed.]",4,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Thomas Mann: profile and perspectives, with two unpublished letters and a chronological list of important events","Von Gronicka, André, 1912-","[1st ed.]",9,"BOOK",0394308433,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Designing houses : an illustrated guide / by Les Walker and Jeff Milstein","Walker, Les.","1st ed.",4,"BOOK",0879510358,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Designing houses : an illustrated guide / by Les Walker and Jeff Milstein","Walker, Les.","1st ed.",5,"BOOK",0879510358,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Modern political philosophies and what they mean","Wasserman, Louis.","2d ed.",7,"BOOK",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A history of Western architecture / David Watkin","Watkin, David, 1941-","3rd ed.",6,"BOOK",0823022730,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("A history of Western architecture / David Watkin","Watkin, David, 1941-","3rd ed.",9,"BOOK",0823022730,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Solo","Whitmore, Stanford, 1925-","[1st ed.]",6,"FICTION ",null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Solo","Whitmore, Stanford, 1925-","[1st ed.]",7,"FICTION ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Anatomy of China  an introduction to one quarter of mankind [by] Dick Wilson","Wilson, Dick, 1928-","2d rev. ed.",7,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Everything you need to know about the dangers of sports gambling / Joshua D.G. Willker","Wilker, Josh.","1st ed.",7,"BOOK",082393229,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Everything you need to know about the dangers of sports gambling / Joshua D.G. Willker","Wilker, Josh.","1st ed.",10,"BOOK",082393229,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Inane, humane and germane  poems","Wilhelm, Louis August, 1903-","[1st ed.]",9,"BOOK",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Sacramento waltz","Williams, Elva.","[1st ed.]",1,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Sacramento waltz","Williams, Elva.","[1st ed.]",4,"FICTION ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Gemarakup super sleuth / by Miriam Stark Zakon   illustrated by Channa Galitzer","Zakon, Miriam Stark.","1st ed.",9,"JOURNAL FICTION ",0899069665,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Applied mathematics for business, economics, life sciences, and social sciences","Barnett, Raymond A.","7th ed. / Raymond A. Barnett",5,"SCIENCE ",null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Applied mathematics for business, economics, life sciences, and social sciences","Barnett, Raymond A.","7th ed. / Raymond A. Barnett",4,"SCIENCE ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Applied mathematics for business, economics, life sciences, and social sciences","Barnett, Raymond A.","7th ed. / Raymond A. Barnett",8,"SCIENCE ",null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Macroeconomics / Timothy Tregarthen, Libby Rittenberg","Tregarthen, Timothy D.","2nd ed.",2,"BOOK",1572594195,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Macroeconomics / Timothy Tregarthen, Libby Rittenberg","Tregarthen, Timothy D.","2nd ed.",10,"BOOK",1572594195,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Tou tou pian le ni / Hongxing","880-01 Hongxing.","880-03 Di 1 ban.",10,"FICTION CHINESE ",986773517,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Tou tou pian le ni / Hongxing","880-01 Hongxing.","880-03 Di 1 ban.",1,"FICTION CHINESE ",986773517,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Tou tou pian le ni / Hongxing","880-01 Hongxing.","880-03 Di 1 ban.",3,"FICTION CHINESE ",986773517,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Availability of SCHIP allotments for fiscal years 1998 through 2001 : report (to accompany S. 312) (including cost estimate of the Congressional Budge","United States. Congress. Senate. Committee on Finance.","[Corr. print.].",3,null,null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Availability of SCHIP allotments for fiscal years 1998 through 2001 : report (to accompany S. 312) (including cost estimate of the Congressional Budge","United States. Congress. Senate. Committee on Finance.","[Corr. print.].",1,null,null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Taming a sea-horse [sound recording] / by Robert B. Parker","Parker, Robert B., 1932-2010.","Library ed.",6,"FICTION AUDIO ",0736617507,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Taming a sea-horse [sound recording] / by Robert B. Parker","Parker, Robert B., 1932-2010.","Library ed.",1,"FICTION AUDIO ",0736617507,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Shashibiya = William Shakespeare / Chen Botong bian zhu","880-01 Chen, Botong.","880-03 Di 1 ban.",5,"CHINESE ",9620417569,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Vision 100--Century of Aviation Reauthorization Act : conference report (to accompany H.R. 2115)","United States. Congress (108th, 1st session : 2003)","[Oct. 29",3,null,null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Vision 100--Century of Aviation Reauthorization Act : conference report (to accompany H.R. 2115)","United States. Congress (108th, 1st session : 2003)","[Oct. 29",6,null,null,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Ethiopia","United States. Central Intelligence Agency.","[Relief ed.].",1,null,null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Leng xiu han dao yi : Zhi zun lei tai / Yu Weipo zhu","880-01 Yu, Weipo.","880-04 Chu ban.",8,"FICTION CHINESE ",9573074400,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mr Midshipman Hornblower / C.S. Forester   retold by Rosemary Border","Border, Rosemary, 1943-","2nd ed.",7,"FICTION ",0194230414,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mr Midshipman Hornblower / C.S. Forester   retold by Rosemary Border","Border, Rosemary, 1943-","2nd ed.",3,"FICTION ",0194230414,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Mr Midshipman Hornblower / C.S. Forester   retold by Rosemary Border","Border, Rosemary, 1943-","2nd ed.",1,"FICTION ",0194230414,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("United States-Morocco Free Trade Agreement Implementation Act : report (to accompany S. 2677) (including cost estimate of the Congressional Budget Off","United States. Congress. Senate. Committee on Finance.","[Corr. print.].",7,null,null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("United States-Morocco Free Trade Agreement Implementation Act : report (to accompany S. 2677) (including cost estimate of the Congressional Budget Off","United States. Congress. Senate. Committee on Finance.","[Corr. print.].",8,null,null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Ping lan you jun / Dong Ni zhu","880-01 Dong, Ni.","880-03 Chu ban.",8,"FICTION CHINESE ",9864241249,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Jia jiao, you wen ti! / Zi Xuan","880-01 Zi, Xuan.","880-03 Chu ban.",1,"FICTION CHINESE ",9574727513,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Jia jiao, you wen ti! / Zi Xuan","880-01 Zi, Xuan.","880-03 Chu ban.",9,"FICTION CHINESE ",9574727513,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Jia jiao, you wen ti! / Zi Xuan","880-01 Zi, Xuan.","880-03 Chu ban.",4,"FICTION CHINESE ",9574727513,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Riddle ju le bu / Piaoyun","880-01 Piaoyun.","880-03 Chu ban.",7,"FICTION CHINESE ",9574726177,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Riddle ju le bu / Piaoyun","880-01 Piaoyun.","880-03 Chu ban.",9,"FICTION CHINESE ",9574726177,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Riddle ju le bu / Piaoyun","880-01 Piaoyun.","880-03 Chu ban.",10,"FICTION CHINESE ",9574726177,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Mi hun qing jie / zhu: Lan Shaofen","880-01 Lan, Shaofen.","880-03 Chu ban.",1,"FICTION CHINESE ",9574912752,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Jue dui yi wai / Zhan Qing zhu","880-01 Zhan, Qing.","880-03 Chu ban.",10,"FICTION CHINESE ",9574711897,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Jue dui yi wai / Zhan Qing zhu","880-01 Zhan, Qing.","880-03 Chu ban.",5,"FICTION CHINESE ",9574711897,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("V poiskakh Goroda Bogov / Ernst Muldashev","Muldashev, Ėrnst.","2-e izd.",9,"RUSSIAN ",5765435351,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-01 Luan zhong qu sheng = Thriving on chaos / Tangmu. Bidesi zhu   Zhu Baochen deng yi","Peters, Thomas J.","880-03 Di 1 ban.",9,"CHINESE ",7805649448,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Saturn illustrated chronology [electronic resource] / prepared by David S. Akens","Akens, David S.","[5th ed.]",2,null,null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Saturn illustrated chronology [electronic resource] / prepared by David S. Akens","Akens, David S.","[5th ed.]",5,null,null,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Saturn illustrated chronology [electronic resource] / prepared by David S. Akens","Akens, David S.","[5th ed.]",10,null,null,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-01 Bu cun zai de nü er / Jin Aidehuazi zhu   Shi Qingzhen yi","Edwards, Kim, 1958-","880-02 Chu ban.",8,"FICTION CHINESE ",9789866973314,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-01 Bu cun zai de nü er / Jin Aidehuazi zhu   Shi Qingzhen yi","Edwards, Kim, 1958-","880-02 Chu ban.",10,"FICTION CHINESE ",9789866973314,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Hua jie yu / Yishu zhu","880-01 Yishu.","880-03 Chu ban.",5,"FICTION CHINESE ",957812290,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("880-02 Hua jie yu / Yishu zhu","880-01 Yishu.","880-03 Chu ban.",3,"FICTION CHINESE ",957812290,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Read better, remember more [electronic resource] / Elizabeth Chesla","Chesla, Elizabeth L.","2nd ed.",10,"EBOOK ",1576853365,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Read better, remember more [electronic resource] / Elizabeth Chesla","Chesla, Elizabeth L.","2nd ed.",1,"EBOOK ",1576853365,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Read better, remember more [electronic resource] / Elizabeth Chesla","Chesla, Elizabeth L.","2nd ed.",6,"EBOOK ",1576853365,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("White teeth [electronic resource] : a novel / Zadie Smith","Smith, Zadie.","1st Vintage International ed.",5,"EBOOK ",9781400075508,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("White teeth [electronic resource] : a novel / Zadie Smith","Smith, Zadie.","1st Vintage International ed.",6,"EBOOK ",9781400075508,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("White teeth [electronic resource] : a novel / Zadie Smith","Smith, Zadie.","1st Vintage International ed.",4,"EBOOK ",9781400075508,2);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The opposite of me : a novel / by Sarah Pekkanen","Pekkanen, Sarah.","1st Washington Square Press trade pbk. ed.",1,"FICTION ",1439121982,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The opposite of me : a novel / by Sarah Pekkanen","Pekkanen, Sarah.","1st Washington Square Press trade pbk. ed.",7,"FICTION ",1439121982,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("The opposite of me : a novel / by Sarah Pekkanen","Pekkanen, Sarah.","1st Washington Square Press trade pbk. ed.",3,"FICTION ",1439121982,1);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Death of a valentine [electronic resource] / M.C. Beaton","Beaton, M. C.","1st eBook ed.",3,"EBOOK ",9780446558433,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Death of a valentine [electronic resource] / M.C. Beaton","Beaton, M. C.","1st eBook ed.",7,"EBOOK ",9780446558433,3);
insert into item(title,author,edition,libraryBranchID,ItemType,standardNumber,copies) values("Death of a valentine [electronic resource] / M.C. Beaton","Beaton, M. C.","1st eBook ed.",10,"EBOOK ",9780446558433,2);

insert into loan(pid,itemid,loanDate,overdue) values (1,2,'2015-11-02',false); 
insert into loan(pid,itemid,loanDate,overdue) values (1,31,'2015-10-05',true); 
insert into loan(pid,itemid,loanDate,overdue) values (2,20,'2015-09-03',true); 
insert into loan(pid,itemid,loanDate,overdue) values (3,19,'2015-11-27',false); 
insert into loan(pid,itemid,loanDate,overdue) values (4,17,'2015-10-19',true); 
insert into loan(pid,itemid,loanDate,overdue) values (6,14,'2015-09-18',false); 
insert into loan(pid,itemid,loanDate,overdue) values (7,13,'2015-11-17',true); 
insert into loan(pid,itemid,loanDate,overdue) values (9,12,'2015-10-05',false); 
insert into loan(pid,itemid,loanDate,overdue) values (10,12,'2015-09-12',true); 
insert into loan(pid,itemid,loanDate,overdue) values (2,10,'2015-11-01',false); 
insert into loan(pid,itemid,loanDate,overdue) values (3,3,'2015-10-10',true); 


insert into rating(ratingdate,itemid,personid,stars) values('2015-04-03',2,1,5);
insert into rating(ratingdate,itemid,personid,stars) values('2014-12-13',3,2,4);
insert into rating(ratingdate,itemid,personid,stars) values('2015-01-23',10,2,5);
insert into rating(ratingdate,itemid,personid,stars) values('2013-04-05',12,3,2);
insert into rating(ratingdate,itemid,personid,stars) values('2015-02-13',40,4,5);
insert into rating(ratingdate,itemid,personid,stars) values('2012-08-23',50,5,4);
insert into rating(ratingdate,itemid,personid,stars) values('2015-05-03',71,6,3);
insert into rating(ratingdate,itemid,personid,stars) values('2014-01-10',81,7,1);
insert into rating(ratingdate,itemid,personid,stars) values('2011-03-09',41,8,2);
insert into rating(ratingdate,itemid,personid,stars) values('2010-04-07',31,9,5);
insert into rating(ratingdate,itemid,personid,stars) values('2015-08-27',51,10,4);
insert into rating(ratingdate,itemid,personid,stars) values('2013-07-13',61,9,4);
insert into rating(ratingdate,itemid,personid,stars) values('2012-06-09',50,8,3);



insert into loan(pid,itemid,loanDate,overdue) values(3,41,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(4,44,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(5,45,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(8,41,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(10,41,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(5,47,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(5,48,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(1,49,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(4,50,'2015-11-14',0);
insert into loan(pid,itemid,loanDate,overdue) values(10,61,'2015-11-14',0);
insert into loan(pid,itemid,loandate,overdue) values(2,2,current_date(),1);


insert into rating(ratingDate,itemid,personid,stars) values("2015-04-02",2,1,4);
insert into rating(ratingDate,itemid,personid,stars) values("2015-04-02",3,2,5);
insert into rating(ratingDate,itemid,personid,stars) values("2015-04-02",4,2,5);
insert into rating(ratingDate,itemid,personid,stars) values("2015-08-02",4,2,5);
insert into rating(ratingDate,itemid,personid,stars) values("2015-08-03",5,2,5);
